https://github.com/Pre-Fortress-2/PF2-Tools/releases/latest/download/PF2-Tools-Linux.zip# syntax=docker/dockerfile:1
# Pre-Fortress 2 server with SourceMod image.
FROM prefortress2/pfsv:latest

RUN apt-get update && apt-get install -y unzip

RUN curl -L https://github.com/Pre-Fortress-2/PF2-Tools/releases/latest/download/PF2-Tools-Linux.zip -o ./pftools.zip && \

RUN unzip -o ./pftools.zip ./sdk/pf2
