name: Build Pre-Fortress 2 images with cached images.

on:
  workflow_dispatch:
  
jobs:
  prefortress_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t prefortress2/pfsv:latest -f ./dockerfiles/Dockerfile.pf
      - name: Docker Push
        run: docker push prefortress2/pfsv:latest
  prefortress_latest-sm:
    runs-on: ubuntu-latest
    needs: prefortress_latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t prefortress2/pfsv:latest-sm -f ./dockerfiles/Dockerfile.pfsm
      - name: Docker Push
        run: docker push prefortress2/pfsv:latest-sm
