name: Build Pre-Fortress 2 images from scratch.

on: 
  workflow_dispatch:
  
jobs:
  prefortress_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t prefortress/pfsv:_cache -f ./dockerfiles/Dockerfile.cache
      - name: Docker Push
        run: docker push prefortress/pfsv:_cache
  prefortress_latest:
    runs-on: ubuntu-latest
    needs: prefortress_cache
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t prefortress/pfsv:latest -f ./dockerfiles/Dockerfile.pf
      - name: Docker Push
        run: docker push prefortress/pfsv:latest
  prefortress_latest-sm:
    runs-on: ubuntu-latest
    needs: prefortress_latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . -t prefortress/pfsv:latest-sm -f ./dockerfiles/Dockerfile.pfsm
      - name: Docker Push
        run: docker push prefortress/pfsv:latest-sm
